/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.10
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QTreeWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QFrame *menu_frame_bottom;
    QPushButton *pbtn_00_MenuBottom;
    QLabel *lbl_00_MenuBottom_pbtn;
    QLabel *lbl_01_MenuBottom_pbtn;
    QPushButton *pbtn_01_MenuBottom;
    QPushButton *pbtn_09_MenuBottom;
    QLabel *lbl_09_MenuBottom_pbtn;
    QFrame *menu_frame_left;
    QPushButton *pbtn_00_MenuLeft;
    QLabel *lbl_00_MenuLeft_pbtn;
    QLabel *lbl_01_MenuLeft_pbtn;
    QPushButton *pbtn_01_MenuLeft;
    QPushButton *pbtn_07_MenuLeft;
    QLabel *lbl_07_MenuLeft_pbtn;
    QPushButton *pbtn_01_MenuLeft_2;
    QLabel *lbl_01_MenuLeft_pbtn_2;
    QPushButton *pbtn_01_MenuLeft_3;
    QLabel *lbl_01_MenuLeft_pbtn_3;
    QFrame *frame;
    QTextEdit *textEdit;
    QFrame *AllAxisFrame;
    QFrame *AllAxisFrameTop;
    QLabel *lbl_X_AxisPosAct_2;
    QLabel *lbl_X_AxisPosAct_4;
    QLabel *lbl_X_AxisPosAct_6;
    QFrame *X_AxisFrame;
    QLabel *lbl_X_AxisPosAct;
    QLabel *lbl_X_AxisPosCMD;
    QLabel *lbl_X_AxisDTG;
    QLabel *lbl_AllAxisDTG;
    QLabel *label_2;
    QLabel *label;
    QLabel *label_3;
    QLabel *label_4;
    QFrame *Y_AxisFrame;
    QLabel *lbl_Y_AxisPosAct;
    QLabel *lbl_Y_AxisPosCMD;
    QLabel *lbl_Y_AxisDTG;
    QLabel *label_5;
    QFrame *Z_AxisFrame;
    QLabel *lbl_Z_AxisPosAct;
    QLabel *lbl_Z_AxisDTG;
    QLabel *lbl_Z_AxisPosCMD;
    QLabel *label_6;
    QFrame *menu_frame_right;
    QPushButton *pbtn_00_MenuRight;
    QLabel *lbl_00_MenuRight_pbtn;
    QLabel *lbl_01_MenuRight_pbtn;
    QPushButton *pbtn_01_MenuRight;
    QPushButton *pbtn_07_MenuRight;
    QLabel *lbl_07_MenuRight_pbtn;
    QFrame *TabWidgetFrame;
    QTabWidget *tabWidget;
    QWidget *tab_2;
    QTextBrowser *tb_StartUpInfo;
    QWidget *tab;
    QTreeWidget *tw_LLX_Symbols;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1920, 1080);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        menu_frame_bottom = new QFrame(centralWidget);
        menu_frame_bottom->setObjectName(QString::fromUtf8("menu_frame_bottom"));
        menu_frame_bottom->setGeometry(QRect(0, 984, 1920, 96));
        menu_frame_bottom->setFrameShape(QFrame::StyledPanel);
        menu_frame_bottom->setFrameShadow(QFrame::Raised);
        pbtn_00_MenuBottom = new QPushButton(menu_frame_bottom);
        pbtn_00_MenuBottom->setObjectName(QString::fromUtf8("pbtn_00_MenuBottom"));
        pbtn_00_MenuBottom->setGeometry(QRect(0, 0, 192, 96));
        pbtn_00_MenuBottom->setBaseSize(QSize(192, 96));
        QFont font;
        font.setPointSize(8);
        pbtn_00_MenuBottom->setFont(font);
        lbl_00_MenuBottom_pbtn = new QLabel(menu_frame_bottom);
        lbl_00_MenuBottom_pbtn->setObjectName(QString::fromUtf8("lbl_00_MenuBottom_pbtn"));
        lbl_00_MenuBottom_pbtn->setGeometry(QRect(152, 12, 28, 12));
        lbl_00_MenuBottom_pbtn->setFrameShape(QFrame::StyledPanel);
        lbl_01_MenuBottom_pbtn = new QLabel(menu_frame_bottom);
        lbl_01_MenuBottom_pbtn->setObjectName(QString::fromUtf8("lbl_01_MenuBottom_pbtn"));
        lbl_01_MenuBottom_pbtn->setGeometry(QRect(344, 12, 28, 12));
        lbl_01_MenuBottom_pbtn->setFrameShape(QFrame::StyledPanel);
        pbtn_01_MenuBottom = new QPushButton(menu_frame_bottom);
        pbtn_01_MenuBottom->setObjectName(QString::fromUtf8("pbtn_01_MenuBottom"));
        pbtn_01_MenuBottom->setGeometry(QRect(192, 0, 192, 96));
        pbtn_01_MenuBottom->setBaseSize(QSize(192, 96));
        pbtn_01_MenuBottom->setFont(font);
        pbtn_09_MenuBottom = new QPushButton(menu_frame_bottom);
        pbtn_09_MenuBottom->setObjectName(QString::fromUtf8("pbtn_09_MenuBottom"));
        pbtn_09_MenuBottom->setGeometry(QRect(1728, 0, 192, 96));
        pbtn_09_MenuBottom->setBaseSize(QSize(192, 96));
        QFont font1;
        font1.setFamily(QString::fromUtf8("DejaVu Sans"));
        font1.setPointSize(20);
        font1.setBold(true);
        font1.setWeight(75);
        pbtn_09_MenuBottom->setFont(font1);
        QIcon icon;
        icon.addFile(QString::fromUtf8("Bitmap/exit_icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbtn_09_MenuBottom->setIcon(icon);
        pbtn_09_MenuBottom->setIconSize(QSize(72, 72));
        lbl_09_MenuBottom_pbtn = new QLabel(menu_frame_bottom);
        lbl_09_MenuBottom_pbtn->setObjectName(QString::fromUtf8("lbl_09_MenuBottom_pbtn"));
        lbl_09_MenuBottom_pbtn->setGeometry(QRect(1882, 12, 28, 12));
        lbl_09_MenuBottom_pbtn->setFrameShape(QFrame::StyledPanel);
        pbtn_00_MenuBottom->raise();
        lbl_00_MenuBottom_pbtn->raise();
        pbtn_01_MenuBottom->raise();
        lbl_01_MenuBottom_pbtn->raise();
        pbtn_09_MenuBottom->raise();
        lbl_09_MenuBottom_pbtn->raise();
        menu_frame_left = new QFrame(centralWidget);
        menu_frame_left->setObjectName(QString::fromUtf8("menu_frame_left"));
        menu_frame_left->setGeometry(QRect(0, 216, 192, 768));
        menu_frame_left->setFrameShape(QFrame::StyledPanel);
        menu_frame_left->setFrameShadow(QFrame::Raised);
        pbtn_00_MenuLeft = new QPushButton(menu_frame_left);
        pbtn_00_MenuLeft->setObjectName(QString::fromUtf8("pbtn_00_MenuLeft"));
        pbtn_00_MenuLeft->setGeometry(QRect(0, 0, 192, 96));
        pbtn_00_MenuLeft->setBaseSize(QSize(192, 96));
        pbtn_00_MenuLeft->setFont(font);
        lbl_00_MenuLeft_pbtn = new QLabel(menu_frame_left);
        lbl_00_MenuLeft_pbtn->setObjectName(QString::fromUtf8("lbl_00_MenuLeft_pbtn"));
        lbl_00_MenuLeft_pbtn->setGeometry(QRect(152, 12, 28, 12));
        lbl_00_MenuLeft_pbtn->setFrameShape(QFrame::StyledPanel);
        lbl_01_MenuLeft_pbtn = new QLabel(menu_frame_left);
        lbl_01_MenuLeft_pbtn->setObjectName(QString::fromUtf8("lbl_01_MenuLeft_pbtn"));
        lbl_01_MenuLeft_pbtn->setGeometry(QRect(152, 108, 28, 12));
        lbl_01_MenuLeft_pbtn->setFrameShape(QFrame::StyledPanel);
        pbtn_01_MenuLeft = new QPushButton(menu_frame_left);
        pbtn_01_MenuLeft->setObjectName(QString::fromUtf8("pbtn_01_MenuLeft"));
        pbtn_01_MenuLeft->setGeometry(QRect(0, 96, 192, 96));
        pbtn_01_MenuLeft->setBaseSize(QSize(192, 96));
        QFont font2;
        font2.setPointSize(24);
        pbtn_01_MenuLeft->setFont(font2);
        pbtn_07_MenuLeft = new QPushButton(menu_frame_left);
        pbtn_07_MenuLeft->setObjectName(QString::fromUtf8("pbtn_07_MenuLeft"));
        pbtn_07_MenuLeft->setGeometry(QRect(0, 672, 192, 96));
        pbtn_07_MenuLeft->setBaseSize(QSize(192, 96));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Sans"));
        font3.setPointSize(8);
        font3.setBold(false);
        font3.setWeight(50);
        font3.setKerning(true);
        pbtn_07_MenuLeft->setFont(font3);
        pbtn_07_MenuLeft->setIconSize(QSize(72, 72));
        lbl_07_MenuLeft_pbtn = new QLabel(menu_frame_left);
        lbl_07_MenuLeft_pbtn->setObjectName(QString::fromUtf8("lbl_07_MenuLeft_pbtn"));
        lbl_07_MenuLeft_pbtn->setGeometry(QRect(152, 684, 28, 12));
        lbl_07_MenuLeft_pbtn->setFrameShape(QFrame::StyledPanel);
        pbtn_01_MenuLeft_2 = new QPushButton(menu_frame_left);
        pbtn_01_MenuLeft_2->setObjectName(QString::fromUtf8("pbtn_01_MenuLeft_2"));
        pbtn_01_MenuLeft_2->setGeometry(QRect(0, 192, 192, 96));
        pbtn_01_MenuLeft_2->setBaseSize(QSize(192, 96));
        pbtn_01_MenuLeft_2->setFont(font);
        lbl_01_MenuLeft_pbtn_2 = new QLabel(menu_frame_left);
        lbl_01_MenuLeft_pbtn_2->setObjectName(QString::fromUtf8("lbl_01_MenuLeft_pbtn_2"));
        lbl_01_MenuLeft_pbtn_2->setGeometry(QRect(150, 210, 28, 12));
        lbl_01_MenuLeft_pbtn_2->setFrameShape(QFrame::StyledPanel);
        pbtn_01_MenuLeft_3 = new QPushButton(menu_frame_left);
        pbtn_01_MenuLeft_3->setObjectName(QString::fromUtf8("pbtn_01_MenuLeft_3"));
        pbtn_01_MenuLeft_3->setGeometry(QRect(0, 288, 192, 96));
        pbtn_01_MenuLeft_3->setBaseSize(QSize(192, 96));
        pbtn_01_MenuLeft_3->setFont(font2);
        lbl_01_MenuLeft_pbtn_3 = new QLabel(menu_frame_left);
        lbl_01_MenuLeft_pbtn_3->setObjectName(QString::fromUtf8("lbl_01_MenuLeft_pbtn_3"));
        lbl_01_MenuLeft_pbtn_3->setGeometry(QRect(150, 310, 28, 12));
        lbl_01_MenuLeft_pbtn_3->setFrameShape(QFrame::StyledPanel);
        pbtn_00_MenuLeft->raise();
        lbl_00_MenuLeft_pbtn->raise();
        pbtn_01_MenuLeft->raise();
        pbtn_07_MenuLeft->raise();
        lbl_07_MenuLeft_pbtn->raise();
        lbl_01_MenuLeft_pbtn->raise();
        pbtn_01_MenuLeft_2->raise();
        lbl_01_MenuLeft_pbtn_2->raise();
        pbtn_01_MenuLeft_3->raise();
        lbl_01_MenuLeft_pbtn_3->raise();
        frame = new QFrame(centralWidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 0, 1920, 216));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        textEdit = new QTextEdit(frame);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(1730, 0, 192, 36));
        QFont font4;
        font4.setFamily(QString::fromUtf8("DejaVu Sans"));
        font4.setPointSize(8);
        textEdit->setFont(font4);
        AllAxisFrame = new QFrame(centralWidget);
        AllAxisFrame->setObjectName(QString::fromUtf8("AllAxisFrame"));
        AllAxisFrame->setGeometry(QRect(192, 216, 720, 288));
        AllAxisFrame->setFrameShape(QFrame::StyledPanel);
        AllAxisFrame->setFrameShadow(QFrame::Raised);
        AllAxisFrameTop = new QFrame(AllAxisFrame);
        AllAxisFrameTop->setObjectName(QString::fromUtf8("AllAxisFrameTop"));
        AllAxisFrameTop->setGeometry(QRect(0, 0, 720, 48));
        AllAxisFrameTop->setFrameShape(QFrame::StyledPanel);
        AllAxisFrameTop->setFrameShadow(QFrame::Raised);
        lbl_X_AxisPosAct_2 = new QLabel(AllAxisFrameTop);
        lbl_X_AxisPosAct_2->setObjectName(QString::fromUtf8("lbl_X_AxisPosAct_2"));
        lbl_X_AxisPosAct_2->setGeometry(QRect(48, 6, 144, 36));
        QFont font5;
        font5.setFamily(QString::fromUtf8("DejaVu Sans"));
        font5.setPointSize(16);
        lbl_X_AxisPosAct_2->setFont(font5);
        lbl_X_AxisPosAct_2->setLayoutDirection(Qt::RightToLeft);
        lbl_X_AxisPosAct_2->setFrameShape(QFrame::StyledPanel);
        lbl_X_AxisPosAct_2->setFrameShadow(QFrame::Raised);
        lbl_X_AxisPosAct_2->setAlignment(Qt::AlignCenter);
        lbl_X_AxisPosAct_4 = new QLabel(AllAxisFrameTop);
        lbl_X_AxisPosAct_4->setObjectName(QString::fromUtf8("lbl_X_AxisPosAct_4"));
        lbl_X_AxisPosAct_4->setGeometry(QRect(492, 6, 144, 36));
        lbl_X_AxisPosAct_4->setFont(font5);
        lbl_X_AxisPosAct_4->setLayoutDirection(Qt::RightToLeft);
        lbl_X_AxisPosAct_4->setFrameShape(QFrame::StyledPanel);
        lbl_X_AxisPosAct_4->setFrameShadow(QFrame::Raised);
        lbl_X_AxisPosAct_4->setAlignment(Qt::AlignCenter);
        lbl_X_AxisPosAct_6 = new QLabel(AllAxisFrameTop);
        lbl_X_AxisPosAct_6->setObjectName(QString::fromUtf8("lbl_X_AxisPosAct_6"));
        lbl_X_AxisPosAct_6->setGeometry(QRect(344, 6, 144, 36));
        lbl_X_AxisPosAct_6->setFont(font5);
        lbl_X_AxisPosAct_6->setLayoutDirection(Qt::RightToLeft);
        lbl_X_AxisPosAct_6->setFrameShape(QFrame::StyledPanel);
        lbl_X_AxisPosAct_6->setFrameShadow(QFrame::Raised);
        lbl_X_AxisPosAct_6->setAlignment(Qt::AlignCenter);
        X_AxisFrame = new QFrame(AllAxisFrame);
        X_AxisFrame->setObjectName(QString::fromUtf8("X_AxisFrame"));
        X_AxisFrame->setGeometry(QRect(0, 48, 720, 48));
        X_AxisFrame->setFrameShape(QFrame::StyledPanel);
        X_AxisFrame->setFrameShadow(QFrame::Raised);
        lbl_X_AxisPosAct = new QLabel(X_AxisFrame);
        lbl_X_AxisPosAct->setObjectName(QString::fromUtf8("lbl_X_AxisPosAct"));
        lbl_X_AxisPosAct->setGeometry(QRect(48, 6, 144, 36));
        lbl_X_AxisPosAct->setFont(font5);
        lbl_X_AxisPosAct->setLayoutDirection(Qt::RightToLeft);
        lbl_X_AxisPosAct->setFrameShape(QFrame::StyledPanel);
        lbl_X_AxisPosAct->setFrameShadow(QFrame::Raised);
        lbl_X_AxisPosAct->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_X_AxisPosAct->setMargin(0);
        lbl_X_AxisPosAct->setIndent(-1);
        lbl_X_AxisPosCMD = new QLabel(X_AxisFrame);
        lbl_X_AxisPosCMD->setObjectName(QString::fromUtf8("lbl_X_AxisPosCMD"));
        lbl_X_AxisPosCMD->setGeometry(QRect(196, 6, 144, 36));
        QFont font6;
        font6.setFamily(QString::fromUtf8("DejaVu Sans"));
        font6.setPointSize(13);
        lbl_X_AxisPosCMD->setFont(font6);
        lbl_X_AxisPosCMD->setLayoutDirection(Qt::RightToLeft);
        lbl_X_AxisPosCMD->setFrameShape(QFrame::StyledPanel);
        lbl_X_AxisPosCMD->setFrameShadow(QFrame::Raised);
        lbl_X_AxisPosCMD->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_X_AxisDTG = new QLabel(X_AxisFrame);
        lbl_X_AxisDTG->setObjectName(QString::fromUtf8("lbl_X_AxisDTG"));
        lbl_X_AxisDTG->setGeometry(QRect(344, 6, 144, 36));
        lbl_X_AxisDTG->setFont(font5);
        lbl_X_AxisDTG->setLayoutDirection(Qt::RightToLeft);
        lbl_X_AxisDTG->setFrameShape(QFrame::StyledPanel);
        lbl_X_AxisDTG->setFrameShadow(QFrame::Raised);
        lbl_X_AxisDTG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_AllAxisDTG = new QLabel(X_AxisFrame);
        lbl_AllAxisDTG->setObjectName(QString::fromUtf8("lbl_AllAxisDTG"));
        lbl_AllAxisDTG->setGeometry(QRect(492, 6, 144, 36));
        lbl_AllAxisDTG->setFont(font5);
        lbl_AllAxisDTG->setLayoutDirection(Qt::RightToLeft);
        lbl_AllAxisDTG->setFrameShape(QFrame::StyledPanel);
        lbl_AllAxisDTG->setFrameShadow(QFrame::Raised);
        lbl_AllAxisDTG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_2 = new QLabel(X_AxisFrame);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(196, 6, 36, 12));
        label_2->setFont(font);
        label_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_2->setIndent(-1);
        label_2->setTextInteractionFlags(Qt::NoTextInteraction);
        label = new QLabel(X_AxisFrame);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(48, 6, 36, 12));
        label->setFont(font);
        label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label->setMargin(0);
        label->setIndent(-1);
        label->setTextInteractionFlags(Qt::NoTextInteraction);
        label_3 = new QLabel(X_AxisFrame);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(344, 6, 36, 12));
        label_3->setFont(font);
        label_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_3->setIndent(-1);
        label_3->setTextInteractionFlags(Qt::NoTextInteraction);
        label_4 = new QLabel(X_AxisFrame);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(0, 6, 44, 36));
        QFont font7;
        font7.setPointSize(16);
        label_4->setFont(font7);
        label_4->setLayoutDirection(Qt::LeftToRight);
        label_4->setFrameShape(QFrame::StyledPanel);
        label_4->setAlignment(Qt::AlignCenter);
        Y_AxisFrame = new QFrame(AllAxisFrame);
        Y_AxisFrame->setObjectName(QString::fromUtf8("Y_AxisFrame"));
        Y_AxisFrame->setGeometry(QRect(0, 96, 720, 48));
        Y_AxisFrame->setFrameShape(QFrame::StyledPanel);
        Y_AxisFrame->setFrameShadow(QFrame::Raised);
        lbl_Y_AxisPosAct = new QLabel(Y_AxisFrame);
        lbl_Y_AxisPosAct->setObjectName(QString::fromUtf8("lbl_Y_AxisPosAct"));
        lbl_Y_AxisPosAct->setGeometry(QRect(48, 6, 144, 36));
        lbl_Y_AxisPosAct->setFont(font5);
        lbl_Y_AxisPosAct->setLayoutDirection(Qt::RightToLeft);
        lbl_Y_AxisPosAct->setFrameShape(QFrame::StyledPanel);
        lbl_Y_AxisPosAct->setFrameShadow(QFrame::Raised);
        lbl_Y_AxisPosAct->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_Y_AxisPosCMD = new QLabel(Y_AxisFrame);
        lbl_Y_AxisPosCMD->setObjectName(QString::fromUtf8("lbl_Y_AxisPosCMD"));
        lbl_Y_AxisPosCMD->setGeometry(QRect(196, 6, 144, 36));
        lbl_Y_AxisPosCMD->setFont(font6);
        lbl_Y_AxisPosCMD->setLayoutDirection(Qt::RightToLeft);
        lbl_Y_AxisPosCMD->setFrameShape(QFrame::StyledPanel);
        lbl_Y_AxisPosCMD->setFrameShadow(QFrame::Raised);
        lbl_Y_AxisPosCMD->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_Y_AxisDTG = new QLabel(Y_AxisFrame);
        lbl_Y_AxisDTG->setObjectName(QString::fromUtf8("lbl_Y_AxisDTG"));
        lbl_Y_AxisDTG->setGeometry(QRect(344, 6, 144, 36));
        lbl_Y_AxisDTG->setFont(font5);
        lbl_Y_AxisDTG->setLayoutDirection(Qt::RightToLeft);
        lbl_Y_AxisDTG->setFrameShape(QFrame::StyledPanel);
        lbl_Y_AxisDTG->setFrameShadow(QFrame::Raised);
        lbl_Y_AxisDTG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_5 = new QLabel(Y_AxisFrame);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(0, 6, 44, 36));
        label_5->setFont(font7);
        label_5->setLayoutDirection(Qt::LeftToRight);
        label_5->setFrameShape(QFrame::StyledPanel);
        label_5->setAlignment(Qt::AlignCenter);
        Z_AxisFrame = new QFrame(AllAxisFrame);
        Z_AxisFrame->setObjectName(QString::fromUtf8("Z_AxisFrame"));
        Z_AxisFrame->setGeometry(QRect(0, 144, 720, 48));
        Z_AxisFrame->setFrameShape(QFrame::StyledPanel);
        Z_AxisFrame->setFrameShadow(QFrame::Raised);
        lbl_Z_AxisPosAct = new QLabel(Z_AxisFrame);
        lbl_Z_AxisPosAct->setObjectName(QString::fromUtf8("lbl_Z_AxisPosAct"));
        lbl_Z_AxisPosAct->setGeometry(QRect(48, 6, 144, 36));
        lbl_Z_AxisPosAct->setFont(font5);
        lbl_Z_AxisPosAct->setLayoutDirection(Qt::RightToLeft);
        lbl_Z_AxisPosAct->setFrameShape(QFrame::StyledPanel);
        lbl_Z_AxisPosAct->setFrameShadow(QFrame::Raised);
        lbl_Z_AxisPosAct->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_Z_AxisDTG = new QLabel(Z_AxisFrame);
        lbl_Z_AxisDTG->setObjectName(QString::fromUtf8("lbl_Z_AxisDTG"));
        lbl_Z_AxisDTG->setGeometry(QRect(344, 6, 144, 36));
        lbl_Z_AxisDTG->setFont(font5);
        lbl_Z_AxisDTG->setLayoutDirection(Qt::RightToLeft);
        lbl_Z_AxisDTG->setFrameShape(QFrame::StyledPanel);
        lbl_Z_AxisDTG->setFrameShadow(QFrame::Raised);
        lbl_Z_AxisDTG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_Z_AxisPosCMD = new QLabel(Z_AxisFrame);
        lbl_Z_AxisPosCMD->setObjectName(QString::fromUtf8("lbl_Z_AxisPosCMD"));
        lbl_Z_AxisPosCMD->setGeometry(QRect(196, 6, 144, 36));
        lbl_Z_AxisPosCMD->setFont(font6);
        lbl_Z_AxisPosCMD->setLayoutDirection(Qt::RightToLeft);
        lbl_Z_AxisPosCMD->setFrameShape(QFrame::StyledPanel);
        lbl_Z_AxisPosCMD->setFrameShadow(QFrame::Raised);
        lbl_Z_AxisPosCMD->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_6 = new QLabel(Z_AxisFrame);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(0, 6, 44, 36));
        label_6->setFont(font7);
        label_6->setLayoutDirection(Qt::LeftToRight);
        label_6->setFrameShape(QFrame::StyledPanel);
        label_6->setAlignment(Qt::AlignCenter);
        menu_frame_right = new QFrame(centralWidget);
        menu_frame_right->setObjectName(QString::fromUtf8("menu_frame_right"));
        menu_frame_right->setGeometry(QRect(1728, 216, 192, 768));
        menu_frame_right->setFrameShape(QFrame::StyledPanel);
        menu_frame_right->setFrameShadow(QFrame::Raised);
        pbtn_00_MenuRight = new QPushButton(menu_frame_right);
        pbtn_00_MenuRight->setObjectName(QString::fromUtf8("pbtn_00_MenuRight"));
        pbtn_00_MenuRight->setGeometry(QRect(0, 0, 192, 96));
        pbtn_00_MenuRight->setBaseSize(QSize(192, 96));
        lbl_00_MenuRight_pbtn = new QLabel(menu_frame_right);
        lbl_00_MenuRight_pbtn->setObjectName(QString::fromUtf8("lbl_00_MenuRight_pbtn"));
        lbl_00_MenuRight_pbtn->setGeometry(QRect(152, 12, 28, 12));
        lbl_00_MenuRight_pbtn->setFrameShape(QFrame::StyledPanel);
        lbl_01_MenuRight_pbtn = new QLabel(menu_frame_right);
        lbl_01_MenuRight_pbtn->setObjectName(QString::fromUtf8("lbl_01_MenuRight_pbtn"));
        lbl_01_MenuRight_pbtn->setGeometry(QRect(152, 108, 28, 12));
        lbl_01_MenuRight_pbtn->setFrameShape(QFrame::StyledPanel);
        pbtn_01_MenuRight = new QPushButton(menu_frame_right);
        pbtn_01_MenuRight->setObjectName(QString::fromUtf8("pbtn_01_MenuRight"));
        pbtn_01_MenuRight->setGeometry(QRect(0, 96, 192, 96));
        pbtn_01_MenuRight->setBaseSize(QSize(192, 96));
        pbtn_07_MenuRight = new QPushButton(menu_frame_right);
        pbtn_07_MenuRight->setObjectName(QString::fromUtf8("pbtn_07_MenuRight"));
        pbtn_07_MenuRight->setGeometry(QRect(0, 672, 192, 96));
        pbtn_07_MenuRight->setBaseSize(QSize(192, 96));
        QFont font8;
        font8.setFamily(QString::fromUtf8("Sans"));
        font8.setPointSize(10);
        font8.setBold(false);
        font8.setWeight(50);
        font8.setKerning(true);
        pbtn_07_MenuRight->setFont(font8);
        pbtn_07_MenuRight->setIconSize(QSize(72, 72));
        lbl_07_MenuRight_pbtn = new QLabel(menu_frame_right);
        lbl_07_MenuRight_pbtn->setObjectName(QString::fromUtf8("lbl_07_MenuRight_pbtn"));
        lbl_07_MenuRight_pbtn->setGeometry(QRect(152, 684, 28, 12));
        lbl_07_MenuRight_pbtn->setFrameShape(QFrame::StyledPanel);
        pbtn_00_MenuRight->raise();
        lbl_00_MenuRight_pbtn->raise();
        pbtn_01_MenuRight->raise();
        pbtn_07_MenuRight->raise();
        lbl_07_MenuRight_pbtn->raise();
        lbl_01_MenuRight_pbtn->raise();
        TabWidgetFrame = new QFrame(centralWidget);
        TabWidgetFrame->setObjectName(QString::fromUtf8("TabWidgetFrame"));
        TabWidgetFrame->setGeometry(QRect(912, 216, 816, 384));
        TabWidgetFrame->setFrameShape(QFrame::StyledPanel);
        TabWidgetFrame->setFrameShadow(QFrame::Raised);
        tabWidget = new QTabWidget(TabWidgetFrame);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 816, 384));
        tabWidget->setAutoFillBackground(false);
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        tb_StartUpInfo = new QTextBrowser(tab_2);
        tb_StartUpInfo->setObjectName(QString::fromUtf8("tb_StartUpInfo"));
        tb_StartUpInfo->setGeometry(QRect(0, 0, 816, 354));
        QFont font9;
        font9.setPointSize(12);
        tb_StartUpInfo->setFont(font9);
        tb_StartUpInfo->setFrameShadow(QFrame::Plain);
        tabWidget->addTab(tab_2, QString());
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        tw_LLX_Symbols = new QTreeWidget(tab);
        QTreeWidgetItem *__qtreewidgetitem = new QTreeWidgetItem();
        __qtreewidgetitem->setText(2, QString::fromUtf8("3"));
        __qtreewidgetitem->setText(1, QString::fromUtf8("2"));
        __qtreewidgetitem->setText(0, QString::fromUtf8("1"));
        tw_LLX_Symbols->setHeaderItem(__qtreewidgetitem);
        tw_LLX_Symbols->setObjectName(QString::fromUtf8("tw_LLX_Symbols"));
        tw_LLX_Symbols->setGeometry(QRect(0, 0, 816, 354));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(tw_LLX_Symbols->sizePolicy().hasHeightForWidth());
        tw_LLX_Symbols->setSizePolicy(sizePolicy);
        tw_LLX_Symbols->setFont(font9);
        tw_LLX_Symbols->setFrameShadow(QFrame::Plain);
        tw_LLX_Symbols->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        tw_LLX_Symbols->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tw_LLX_Symbols->setAutoScroll(true);
        tw_LLX_Symbols->setAlternatingRowColors(true);
        tw_LLX_Symbols->setColumnCount(3);
        tw_LLX_Symbols->header()->setCascadingSectionResizes(true);
        tw_LLX_Symbols->header()->setDefaultSectionSize(99);
        tw_LLX_Symbols->header()->setHighlightSections(true);
        tw_LLX_Symbols->header()->setProperty("showSortIndicator", QVariant(true));
        tabWidget->addTab(tab, QString());
        MainWindow->setCentralWidget(centralWidget);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        pbtn_00_MenuBottom->setText(QApplication::translate("MainWindow", "pbtn_B_00", nullptr));
        lbl_00_MenuBottom_pbtn->setText(QString());
        lbl_01_MenuBottom_pbtn->setText(QString());
        pbtn_01_MenuBottom->setText(QApplication::translate("MainWindow", "pbtn_B_01", nullptr));
        pbtn_09_MenuBottom->setText(QString());
        lbl_09_MenuBottom_pbtn->setText(QString());
        pbtn_00_MenuLeft->setText(QApplication::translate("MainWindow", "pbtn_L_00", nullptr));
        lbl_00_MenuLeft_pbtn->setText(QString());
        lbl_01_MenuLeft_pbtn->setText(QString());
        pbtn_01_MenuLeft->setText(QApplication::translate("MainWindow", "AXIS", nullptr));
        pbtn_07_MenuLeft->setText(QApplication::translate("MainWindow", "pbtn_L_07", nullptr));
        lbl_07_MenuLeft_pbtn->setText(QString());
        pbtn_01_MenuLeft_2->setText(QApplication::translate("MainWindow", "pbtn_L_02", nullptr));
        lbl_01_MenuLeft_pbtn_2->setText(QString());
        pbtn_01_MenuLeft_3->setText(QApplication::translate("MainWindow", "CNC", nullptr));
        lbl_01_MenuLeft_pbtn_3->setText(QString());
        lbl_X_AxisPosAct_2->setText(QApplication::translate("MainWindow", "PCS", nullptr));
        lbl_X_AxisPosAct_4->setText(QApplication::translate("MainWindow", "AllAxis_DTG", nullptr));
        lbl_X_AxisPosAct_6->setText(QApplication::translate("MainWindow", "DTG", nullptr));
        lbl_X_AxisPosAct->setText(QApplication::translate("MainWindow", "X_Axis_TCP", nullptr));
        lbl_X_AxisPosCMD->setText(QApplication::translate("MainWindow", "X_Axis_CMD", nullptr));
        lbl_X_AxisDTG->setText(QApplication::translate("MainWindow", "DTG", nullptr));
        lbl_AllAxisDTG->setText(QApplication::translate("MainWindow", "AllAxis_DTG", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "CMD", nullptr));
        label->setText(QApplication::translate("MainWindow", "ACT", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "DTG", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "X", nullptr));
        lbl_Y_AxisPosAct->setText(QApplication::translate("MainWindow", "Y_Axis_TCP", nullptr));
        lbl_Y_AxisPosCMD->setText(QApplication::translate("MainWindow", "Y_Axis_CMD", nullptr));
        lbl_Y_AxisDTG->setText(QApplication::translate("MainWindow", "DTG_Y", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Y", nullptr));
        lbl_Z_AxisPosAct->setText(QApplication::translate("MainWindow", "Z_Axis_TCP", nullptr));
        lbl_Z_AxisDTG->setText(QApplication::translate("MainWindow", "DTG_Z", nullptr));
        lbl_Z_AxisPosCMD->setText(QApplication::translate("MainWindow", "Z_Axis_CMD", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "Z", nullptr));
        pbtn_00_MenuRight->setText(QApplication::translate("MainWindow", "PushButton", nullptr));
        lbl_00_MenuRight_pbtn->setText(QString());
        lbl_01_MenuRight_pbtn->setText(QString());
        pbtn_01_MenuRight->setText(QApplication::translate("MainWindow", "PushButton", nullptr));
        pbtn_07_MenuRight->setText(QApplication::translate("MainWindow", "PushButton", nullptr));
        lbl_07_MenuRight_pbtn->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "StartUp Info", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "LLX Symbols", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
